ci: use scp with sshpass instead of drone-scp from appleboy@scp-action

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -28,32 +28,36 @@ jobs:
       - name: Build
         run: pnpm build
 
-      - name: Delete old build files
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USERNAME }}
-          password: ${{ secrets.SERVER_PASSWORD }}
-          script: |
-            rm -rf ~/app/hasbi3/{dist,node_modules}
+      - name: Check for sshpass installation
+        run: |
+          if ! command -v sshpass &> /dev/null
+          then
+            echo "sshpass not found, installing..."
+            sudo apt-get update && sudo apt-get install -y sshpass
+          else
+            echo "sshpass is already installed"
+          fi
+
+      - name: Delete old build files on server
+        run: |
+          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
+            ssh \
+            -o StrictHostKeyChecking=no \
+            ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} \
+            'rm -rf ~/app/hasbi3/{dist,node_modules}'
 
       - name: Copy build files to server
-        uses: appleboy/scp-action@master
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USERNAME }}
-          password: ${{ secrets.SERVER_PASSWORD }}
-          source: "dist/,node_modules/,ecosystem.config.js"
-          target: "~/app/hasbi3/"
-          overwrite: true
-          timeout: 1m
+        run: |
+          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
+            scp \
+            -o StrictHostKeyChecking=no \
+            -r dist node_modules ecosystem.config.js \
+            ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:~/app/hasbi3/
 
       - name: Deploy to Server
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.SERVER_HOST }}
-          username: ${{ secrets.SERVER_USERNAME }}
-          password: ${{ secrets.SERVER_PASSWORD }}
-          script: |
-            cd ~/app/hasbi3/
-            pm2 startOrRestart ecosystem.config.js
+        run: |
+          sshpass -p "${{ secrets.SERVER_PASSWORD }}" \
+            ssh \
+            -o StrictHostKeyChecking=no \
+            ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} \
+            'cd ~/app/hasbi3/ && pm2 startOrRestart ecosystem.config.js'
